mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import *

app_name = "myauth"



urlpatterns = [
    path("login/",
         LoginView.as_view(
         template_name="myauth/login.html",
         redirect_authenticated_user=True),
         name="login"),
    path("logout/", MyLogoutPage.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="get_cookie"),
    path("cookie/set/", set_cookie_view, name="set_cookie"),
    path("session/get/", get_session_view, name="get_session"),
    path("session/set/", set_session_view, name="set_session"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path('users/', UsersListView.as_view(), name='users-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('users/<int:pk>/avatar/', AvatarUpdateView.as_view(), name='avatar-update'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView,SpectacularSwaggerView
from mysite import settings
from .sitemap import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="sitemap",
    )
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include("debug_toolbar.urls"))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
)

mysite/shopapp/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter

from .views import *

app_name = "shopapp"

router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('orders', OrderViewSet)

urlpatterns = [
    path("", shop_index, name="index"),
    path("api/", include(router.urls)),
    path("groups/", groups_list, name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="products_detail"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("orders/<int:user_id>/json/", get_user_orders_json, name="order_json"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders_list"),
    path("products/create/", CreateProductView.as_view(), name="create_product"),
    path("products/<int:pk>/update/", UpdateProductView.as_view(), name="update_product"),
    path("products/<int:pk>/archive/", ArchiveProductView.as_view(), name="archive_product"),
    path("orders/make/",CreateOrderView.as_view(),name="create_order"),
    path("orders/<int:pk>/update/", UpdateOrderView.as_view(), name="update_order"),
    path("orders/<int:pk>/delete/", DeleteOrderView.as_view(), name="delete_order"),
    path('orders/export/', orders_export_view, name='orders_export'),
    path("hello/", Flan.as_view(), name="hello"),
    path('products/latest/feed/', LatestProductsFeed(), name='product_feed'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]
        permissions = [
            ("can_create_product", "Can create product"),
        ]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')

    # @property
    # def description_short(self):
    #     if len(self.description) < 50:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse('shopapp:products_detail', kwargs={'pk': self.pk})


class Order(models.Model):
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

mysite/shopapp/forms.py
from django import forms

from shopapp.models import Product,Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','price','description']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'products','promocode','delivery_address']
        widgets = {
            'products': forms.CheckboxSelectMultiple,
        }


class CSVImportForm(forms.Form):
    csv_file = forms.FileField(label="Choose a CSV File")

mysite/shopapp/views.py
import json
from timeit import default_timer

from django.contrib.syndication.views import Feed
from django.contrib.sitemaps import Sitemap
from django.core.cache import cache
from django.core.serializers import serialize
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import Group, User
from django.http import HttpResponse, HttpRequest, HttpResponseForbidden, JsonResponse, Http404
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView,DeleteView,UpdateView,ListView,DetailView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets,filters
from .serializers import ProductSerializer,OrderSerializer
from .forms import ProductForm, OrderForm
from .models import Product, Order
import logging

logger = logging.getLogger(__name__)

class LatestProductsFeed(Feed):
    title = "Latest Products"
    link = "/products/latest/feed/"
    description = "New products added to the shop"

    def items(self):
        return Product.objects.order_by('-id')[:5]

    def item_title(self, item):
        return item.name

    def item_description(self, item):
        return f"Price: {item.price}"

    def item_link(self, item):
        return item.get_absolute_url()

class ShopSitemap(Sitemap):
    changefreq = 'never'
    priority = 0.5

    def items(self):
        return Product.objects.order_by('-created_at')

    def lastmod(self, obj):
        return obj.created_at


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['name', 'description']
    ordering_fields = ['price', 'created_at', 'name']


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = ['user', 'created_at']
    ordering_fields = ['created_at']


class Flan(View):
    def get(self, request):
        message = _("Hello, world!")
        return HttpResponse(f"<h1>{message}<h1>")

@cache_page(60)
def shop_index(request: HttpRequest):
    products = [
        ('Laptop', 1999),
        ('Desktop', 2999),
        ('Smartphone', 999),
    ]
    context = {
        "time_running": default_timer(),
        "products": products,
    }
    logger.info("Hello")
    return render(request, 'shopapp/shop-index.html', context=context)


def groups_list(request: HttpRequest):
    context = {
        "groups": Group.objects.prefetch_related('permissions').all(),
    }
    return render(request, 'shopapp/groups-list.html', context=context)


class ProductListView(ListView):
    model = Product()
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter()

class ProductDetailView(DetailView):
    model = Product
    template_name = 'shopapp/product-detail.html'
    context_object_name = 'product'

class CreateProductView(CreateView):
    model = Product
    template_name = 'shopapp/create-product.html'
    form_class = ProductForm
    permission_required = 'shopapp.can_create_product'
    raise_exception = True
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class UpdateProductView(UpdateView):
    model = Product
    template_name = 'shopapp/update-product.html'
    form_class = ProductForm
    success_url = reverse_lazy('shopapp:products_list')
    permission_required = 'shopapp.can_update_product'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()

        if obj.user.is_superuser:
            return super().dispatch(request, *args, **kwargs)

        if not request.user.has_perm('shopapp.can_update_product'):
            return HttpResponseForbidden("You don't have permission to edit this product.")

        if  obj.created_by != request.user:
            return HttpResponseForbidden("You can only edit products you created.")

        return super().dispatch(request, *args, **kwargs)

class ArchiveProductView(View):
    template_name = 'shopapp/archive-product.html'

    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        return render(request, self.template_name, {'product': product})

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.archived = True
        product.save()
        return redirect(reverse_lazy('shopapp:products_list'))

class OrderListView(ListView):
    model = Order
    template_name = 'shopapp/orders-list.html'
    context_object_name = 'orders'

class OrderDetailView(PermissionRequiredMixin,DetailView):
    model = Order
    template_name = 'shopapp/order-detail.html'
    context_object_name = 'order'
    permission_required = 'shopapp.view_order'

class UserOrdersListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'shopapp/user_orders_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        user_id = self.kwargs.get('user_id')
        try:
            self.owner = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            raise Http404("User not found")

        return Order.objects.filter(user=self.owner).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context


def get_user_orders_json(request, user_id):
    cache_key = f"user_orders_export_json_{user_id}"
    cached_data = cache.get(cache_key)

    if cached_data:
        return JsonResponse(cached_data, safe=False)

    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        raise Http404("User not found")

    orders = Order.objects.filter(user=user).order_by('id')

    serialized_data = serialize('json', orders, fields=('delivery_address', 'promocode', 'created_at', 'products'))

    data = json.loads(serialized_data)

    cache.set(cache_key, data, timeout=300)

    return JsonResponse(data, safe=False)

class CreateOrderView(CreateView):
    model = Order
    template_name = 'shopapp/create-order.html'
    form_class = OrderForm
    success_url = reverse_lazy('shopapp:orders_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class UpdateOrderView(UpdateView):
    model = Order
    template_name = 'shopapp/update-order.html'
    form_class = OrderForm
    success_url = reverse_lazy('shopapp:orders_list')


class DeleteOrderView(View):
    template_name = 'shopapp/delete-order.html'

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        return render(request, self.template_name, {'order': order})

    def post(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        order.delete()
        return redirect(reverse_lazy('shopapp:orders_list'))

@user_passes_test(lambda u: u.is_staff)
def orders_export_view(request):
    orders = Order.objects.all().prefetch_related('products')
    data = {
        "orders": [
            {
                "id": order.id,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,
                "user_id": order.user.id,
                "product_ids": list(order.products.values_list('id', flat=True)),
            }
            for order in orders
        ]
    }
    return JsonResponse(data)

mysite/shopapp/templates/shopapp/archive-product.html
{% extends "shopapp/base.html" %}

{% block title %}
  Archive Product
{% endblock %}

{% block body %}
  <h2>Are you sure you want to archive "{{ product.name }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, archive</button>
    <a href="{% url 'shopapp:products_list' %}">Cancel</a>
  </form>
{% endblock %}

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create Order
{% endblock %}

{% block body %}
<h1>Create New Order</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Order</button>
</form>

<p><a href="{% url 'shopapp:orders_list' %}">← Back to Orders</a></p>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create Product
{% endblock %}

{% block body %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Submit
        </button>

    </form>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/delete-order.html
{% extends "shopapp/base.html" %}

{% block title %}
  Delete Order
{% endblock %}

{% block body %}
  <h2>Delete Order #{{ order.pk }}</h2>
  <p>Are you sure you want to <strong>permanently delete</strong> this order made by {{ order.user }}?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'shopapp:orders_list' %}">Cancel</a>
  </form>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order-detail.html
{% extends "shopapp/base.html" %}

{% block title %}
  Order #{{ order.pk }} Details
{% endblock %}

{% block body %}
  <h1>Order #{{ order.pk }}</h1>

  <p><strong>User:</strong> {{ order.user.username }}</p>
  <p><strong>Delivery address:</strong> {{ order.delivery_address }}</p>
  <p><strong>Promo code:</strong> {{ order.promocode }}</p>

  <h2>Products:</h2>
  <ul>
    {% for product in order.products.all %}
      <li>{{ product.name }} – {{ product.price }}$</li>
    {% empty %}
      <li>No products in this order.</li>
    {% endfor %}
  </ul>

  <p><a href="{% url 'shopapp:orders_list' %}">← Back to orders list</a></p>
{% endblock %}

mysite/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if orders %}
    <div>
      {% for order in orders %}
        <div>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/product-detail.html
{% extends "shopapp/base.html" %}
{% load i18n %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block body %}
    <h2>{{ product.name }}</h2>
    <p>{% translate "Price" %}: {{ product.price }} $</p>
    <p>
        {% blocktranslate %}
            Description: {{ product.description }}
        {% endblocktranslate %}
    </p>

    <p>
        <a href="{% url 'shopapp:products_list' %}">
            {% translate "← Back to product list" %}
        </a>
    </p>

    <p>
        <a href="{% url 'shopapp:update_product' pk=product.pk %}">
            {% translate "Update Product" %}
        </a>
    </p>

    <p>
        <a href="{% url 'shopapp:archive_product' pk=product.pk %}">
            {% translate "Archive Product" %}
        </a>
    </p>


    {% blocktranslate count order_count=product.orders.count %}
        This product is used in {{ order_count }} order.
    {% plural %}
        This product is used in {{ order_count }} orders.
    {% endblocktranslate %}

{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  {% if products %}
    <div>
      {% for product in products %}
          <p>
            <strong>Name:</strong>
            <a href="{% url 'shopapp:products_detail' pk=product.pk %}">
              {{ product.name }}
            </a>
          </p>
          <p><strong>Price:</strong> {{ product.price }}</p>
          <p><strong>Discount:</strong> {% firstof product.discount 'no discount' %}</p>
          <p><strong>Archived:</strong>
            {% if product.archived %}
              ✅ Yes
            {% else %}
              ❌ No
            {% endif %}
          </p>
          <hr>
      {% endfor %}
    </div>
  {% else %}
    <h3>No products yet</h3>
  {% endif %}

    {% if perms.shopapp.can_create_product %}
    <a href="{% url 'shopapp:create_product' %}">➕ Create Product</a>
    {% else %}
        <h3>You don't have required permission</h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
        {% if name|length == 7 %}
          <span>Lucky product!</span>
        {% endif %}
      {% empty %}
        No products here
      {% endfor %}

    </ul>
  </div>

  <div>
    Time running: {{ time_running }}
  </div>

  <div>
    {% lorem 3 p random %}
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/update-order.html
{% extends "shopapp/base.html" %}

{% block title %}
  Update Order
{% endblock %}

{% block body %}
<h1>Update Order #{{ form.instance.pk }}</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update Order</button>
</form>

<p><a href="{% url 'shopapp:orders_list' %}">← Back to Orders</a></p>
{% endblock %}

mysite/shopapp/templates/shopapp/update-product.html
{% extends "shopapp/base.html" %}

{% block title %}
  Update Product
{% endblock %}

{% block body %}
  <h2>Update Product</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
  <p><a href="{% url 'shopapp:products_list' %}">← Back to product list</a></p>
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
Orders
{% endblock %}

{% block body %}
<h2>
    {% if orders %}
        User {{ owner.username }} has done the following orders:
    {% else %}
        User {{ owner.username }} has no orders.
    {% endif %}
</h2>

{% load cache %}
<ul>
    {% for order in orders %}
        <li>
            <a href="{% url 'shopapp:order_detail' pk=order.pk %}">Order №{{ order.pk }}</a>
        </li>
    {% endfor %}
</ul>
{% endcache %}
{% endblock %}