mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import *

app_name = "myauth"



urlpatterns = [
    path("login/",
         LoginView.as_view(
         template_name="myauth/login.html",
         redirect_authenticated_user=True),
         name="login"),
    path("logout/", MyLogoutPage.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="get_cookie"),
    path("cookie/set/", set_cookie_view, name="set_cookie"),
    path("session/get/", get_session_view, name="get_session"),
    path("session/set/", set_session_view, name="set_session"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path('users/', UsersListView.as_view(), name='users-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('users/<int:pk>/avatar/', AvatarUpdateView.as_view(), name='avatar-update'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView,SpectacularSwaggerView
from mysite import settings
from .sitemap import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="sitemap",
    )
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include("debug_toolbar.urls"))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
)

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

def profile_avatar_dir_path(instance, filename):
    user_id = instance.user.id if instance.user else 'unknown'
    return f"profile/avatar_{user_id}/{filename}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=profile_avatar_dir_path, null=True, blank=True)

mysite/myauth/forms.py
# forms.py

from django import forms
from .models import Profile

class AvatarUploadForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']

mysite/myauth/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView,LogoutView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import TemplateView, CreateView, DetailView, ListView, UpdateView
from myauth.forms import AvatarUploadForm
from myauth.models import Profile


# Create your views here.


class MyLogoutPage(View):
    def get(self, request):
        logout(request)
        return redirect('myauth:login')

def get_cookie_view(request):
    favorite_color = request.COOKIES.get('favorite_color', 'blue')
    return HttpResponse(f"Favorite color from cookies is: {favorite_color}")

def set_cookie_view(request):
    response = HttpResponse("Cookie set: favorite_color = green")
    response.set_cookie('favorite_color', 'green', max_age=3600)
    return response

def get_session_view(request):
    visit_count = request.session.get('visit_count', 0)
    return HttpResponse(f"Visit count from session: {visit_count}")

def set_session_view(request):
    request.session['visit_count'] = request.session.get('visit_count', 0) + 1
    return HttpResponse("Visit count updated in session.")

class AboutMeView(LoginRequiredMixin, View):
    template_name = "myauth/about-me.html"

    def get(self, request):
        form = AvatarUploadForm(instance=request.user.profile)
        return render(request, self.template_name, {
            'form': form
        })

    def post(self, request):
        form = AvatarUploadForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('myauth:about-me')
        return render(request, self.template_name, {
            'form': form
        })

class UsersListView(ListView):
    model = User
    template_name = "myauth/users_list.html"
    context_object_name = "users"

class UserDetailView(DetailView):
    model = User
    template_name = "myauth/user_detail.html"
    context_object_name = "user_obj"

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        user = self.object

        Profile.objects.create(user=user)

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')

        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response

class AvatarUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['avatar']
    template_name = "myauth/avatar_update.html"

    def dispatch(self, request, *args, **kwargs):
        profile = self.get_object()
        if request.user != profile.user and not request.user.is_staff:
            raise PermissionDenied("You are not allowed to edit this avatar.")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('myauth:user-detail', kwargs={"pk": self.object.user.pk})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
  About me
{% endblock %}

{% block body %}
  <h1>User info</h1>

  {% if user.is_authenticated %}
    <p>Username: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    {% if  user.profile  %}
      <p>Bio: {{ user.profile.bio }}</p>
    {% endif %}


    <p>Avatar:</p>
    {% if user.profile.avatar %}
      <img src="{{ user.profile.avatar.url }}" alt="Avatar" style="max-height: 200px;">
    {% else %}
      <p>No avatar uploaded.</p>
    {% endif %}

    <h3>Upload new avatar</h3>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/avatar_update.html
{% extends "myauth/base.html" %}

{% block title %}Update Avatar{% endblock %}

{% block body %}
  <h2>Update Avatar for {{ object.user.username }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
      Base Title
    {% endblock %}
    </title>
</head>
<body>
{% block body %}
  Base body
{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}

{% block title %}
  Login
{% endblock %}

{% block body %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log in</button>
  </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
Register
{% endblock %}

{% block body  %}
    <h1>Register</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
  {{ user_obj.username }}
{% endblock %}

{% block body %}
  <h1>{{ user_obj.username }}</h1>
  <p>First name: {{ user_obj.first_name }}</p>
  <p>Last name: {{ user_obj.last_name }}</p>
  <p>Email: {{ user_obj.email }}</p>
  <p>Bio: {{ user_obj.profile.bio }}</p>

  {% if user_obj.profile.avatar %}
    <img src="{{ user_obj.profile.avatar.url }}" alt="Avatar" style="max-height: 200px;">
  {% else %}
    <p>No avatar</p>
  {% endif %}

  {% if request.user == user_obj or request.user.is_staff %}
    <p><a href="{% url 'myauth:avatar-update' user_obj.profile.pk %}">Update Avatar</a></p>
  {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/users_list.html
{% extends 'myauth/base.html' %}

{% block title %}
  Users
{% endblock %}

{% block body %}
  <h1>User List</h1>
  <ul>
    {% for user in users %}
      <li>
        <a href="{% url 'myauth:user-detail' user.pk %}">{{ user.username }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}